# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'info.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_info(object):
    def setupUi(self, info):
        info.setObjectName("info")
        info.resize(470, 283)
        self.return_button = QtWidgets.QPushButton(info)
        self.return_button.setGeometry(QtCore.QRect(360, 240, 93, 28))
        self.return_button.setObjectName("return_button")
        self.verticalLayoutWidget = QtWidgets.QWidget(info)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 440, 119))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.name_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.verticalLayout.addWidget(self.name_label)
        self.version_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.version_label.setFont(font)
        self.version_label.setObjectName("version_label")
        self.verticalLayout.addWidget(self.version_label)
        self.dev_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dev_label.setFont(font)
        self.dev_label.setObjectName("dev_label")
        self.verticalLayout.addWidget(self.dev_label)
        self.dateRelease_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateRelease_label.setFont(font)
        self.dateRelease_label.setObjectName("dateRelease_label")
        self.verticalLayout.addWidget(self.dateRelease_label)
        self.description_textEdit = QtWidgets.QTextEdit(info)
        self.description_textEdit.setGeometry(QtCore.QRect(14, 140, 441, 91))
        self.description_textEdit.setObjectName("description_textEdit")

        self.retranslateUi(info)
        QtCore.QMetaObject.connectSlotsByName(info)

        self.return_button.clicked.connect(lambda: self.closeInfo(info))

    def closeInfo(self, info):
        info.hide()

    def retranslateUi(self, info):
        _translate = QtCore.QCoreApplication.translate
        info.setWindowTitle(_translate("info", "О программе \"Система учёта экспортируемых товаров\" "))
        self.return_button.setText(_translate("info", "Понятно"))
        self.name_label.setText(_translate("info", "Система учёта экспортируемых товаров"))
        self.version_label.setText(_translate("info", "Версия: 1.0"))
        self.dev_label.setText(_translate("info", "Разработчик: Ахметшин Сергей Александрович"))
        self.dateRelease_label.setText(_translate("info", "Дата выпуска: 14 декабря 2024 года"))
        self.description_textEdit.setHtml(_translate("info", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Система учёта экспортируемых товаров – это специализированное программное обеспечение, разработанное для автоматизации и оптимизации процесса управления экспортными операциями. Программа предназначена для упрощения ведения документации, анализа и учёта продаж.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Данная система предназначена для компаний, занимающихся экспортом товаров, и поможет им оптимизировать свои бизнес-процессы, повысить производительность и прибыльность.</p></body></html>"))
